version: '2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  application:
    depends_on:
      - mongodb
    links:
      - "mongodb:mongodb"
    image: dstruct:development
    ports:
      - "8080:5000"
