// Angular
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
// RxJS
import 'rxjs';
// identicon.js
import 'identicon.js';
// moment
import 'moment';
// md5
import 'blueimp-md5';
